const DefCountries = [
  {
    name: "Ukraine",
    capital: "Kiev",
    Currency: "Ukrainian hryvnia",
    region: "Europe",
    flag: "https://restcountries.eu/data/ukr.svg",
    cioc: "UKR",
  },
  {
    name: "Ireland",
    capital: "Dublin",
    Currency: "Euro",
    region: "Europe",
    flag: "https://restcountries.eu/data/irl.svg",
    cioc: "IRL",
  },
  {
    name: "Cook Islands",
    capital: "Avaure",
    Currency: "New Zealand Dollar",
    region: "Oceaina",
    flag: "https://restcountries.eu/data/cok.svg",
    cioc: "COK",
  },
  {
    name: "Germany",
    capital: "Berlin",
    Currency: "Euro",
    region: "Europe",
    flag: "https://restcountries.eu/data/deu.svg",
    cioc: "DEU",
  },
  {
    name: "Turkey",
    capital: "Ankara",
    Currency: "Turkish Lira",
    region: "Asia",
    flag: "https://restcountries.eu/data/tur.svg",
    cioc: "TR",
  },
  {
    name: "Azerbaijan",
    capital: "Baku",
    Currency: "Azerbaijani Manat",
    region: "Asia",
    flag: "https://restcountries.eu/data/aze.svg",
    cioc: "AZE",
  },
  {
    name: "Netherlands",
    capital: "Amsterdam",
    Currency: "Euro",
    region: "Europe",
    flag: "https://restcountries.eu/data/nld.svg",
    cioc: "NLD",
  },
  {
    name: "South Africa",
    capital: "Pretoria",
    Currency: "South African Rand",
    region: "Africa",
    flag: "https://restcountries.eu/data/zaf.svg",
    cioc: "ZAF",
  },
  {
    name: "Norway",
    capital: "Norwegian Krone",
    Currency: "Euro",
    region: "Europe",
    flag: "https://restcountries.eu/data/nor.svg",
    cioc: "NOsout",
  },
];

export default DefCountries;
