const DefCountries = [
  {
    name: "Ukraine",
    capital: "Kiev",
    currency: "Ukrainian hryvnia",
    region: "Europe",
    flag: "https://restcountries.eu/data/ukr.svg",
    cioc: "UKR",
    numericCode: "804",
  },
  {
    name: "Ireland",
    capital: "Dublin",
    currency: "Euro",
    region: "Europe",
    flag: "https://restcountries.eu/data/irl.svg",
    cioc: "IRL",
    numericCode: "372",
  },
  {
    name: "Cook Islands",
    capital: "Avaure",
    currency: "New Zealand Dollar",
    region: "Oceaina",
    flag: "https://restcountries.eu/data/cok.svg",
    cioc: "COK",
    numericCode: "184",
  },
  {
    name: "Germany",
    capital: "Berlin",
    currency: "Euro",
    region: "Europe",
    flag: "https://restcountries.eu/data/deu.svg",
    cioc: "DEU",
    numericCode: "276",
  },
  {
    name: "Turkey",
    capital: "Ankara",
    currency: "Turkish Lira",
    region: "Asia",
    flag: "https://restcountries.eu/data/tur.svg",
    cioc: "TR",
    numericCode: "792",
  },
  {
    name: "Azerbaijan",
    capital: "Baku",
    currency: "Azerbaijani Manat",
    region: "Asia",
    flag: "https://restcountries.eu/data/aze.svg",
    cioc: "AZE",
    numericCode: "031",
  },
  {
    name: "Netherlands",
    capital: "Amsterdam",
    currency: "Euro",
    region: "Europe",
    flag: "https://restcountries.eu/data/nld.svg",
    cioc: "NLD",
    numericCode: "528",
  },
  {
    name: "South Africa",
    capital: "Pretoria",
    currency: "South African Rand",
    region: "Africa",
    flag: "https://restcountries.eu/data/zaf.svg",
    cioc: "ZAF",
    numericCode: "710",
  },
  {
    name: "Norway",
    capital: "Norwegian Krone",
    currency: "Euro",
    region: "Europe",
    flag: "https://restcountries.eu/data/nor.svg",
    cioc: "NOR",
    numericCode: "578",
  },
];

export default DefCountries;
